START TRANSACTION;

CREATE TABLE  IF NOT EXISTS `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(512) COLLATE utf8_bin NOT NULL,
  `ord` int(8) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `objects` ADD COLUMN `cat_ref` INT(11) NULL DEFAULT 0 ;

COMMIT;